apiVersion: placement.kubernetes-fleet.io/v1beta1
kind: ClusterStagedUpdateStrategy
metadata:
  name: example-cluster-staged-strategy
spec:
  stages:
    - name: staging
      labelSelector:
        matchLabels:
          environment: staging
      afterStageTasks:
        - type: Approval
    - name: prod
      labelSelector:
        matchLabels:
          environment: prod
      afterStageTasks:
        - type: Approval
